/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as usdcTransferCengliSol from "./USDCTransferCengli.sol";
export type { usdcTransferCengliSol };
