name: cengli
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.2.2
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3

  # State
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0
  provider: ^6.0.5

  # Injector
  get_it: ^7.2.0

  # Firebase
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2
  firebase_remote_config: ^4.2.6
  firebase_core: ^2.16.0
  firebase_dynamic_links: ^5.3.7

  # Auth
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^4.3.0
  crypto: ^3.0.3

  # Model
  equatable: ^2.0.3
  json_serializable: ^6.6.0
  json_annotation: ^4.8.0
  sqflite: ^2.2.6
  uuid: ^3.0.7
  shared_preferences: ^2.2.1

  # Network
  dio: ^4.0.6
  jwt_decoder: ^2.0.1
  web3dart: ^2.5.2
  bip32: ^2.0.0
  bip39: ^1.0.6
  webauthn: ^0.2.1
  local_auth: ^2.1.7
  cbor: ^6.1.1
  eth_sig_util: ^0.0.9
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.7
  ethers: ^0.0.1+3

  # Push Protocol
  hex: ^0.2.0
  pointycastle: ^3.7.3
  openpgp: ^3.7.0
  cryptography: ^2.5.0
  dart_pg: ^1.1.5
  encrypt: ^5.0.1
  flutter_webrtc: ^0.9.36
  ethereum_addresses: ^1.0.2
  socket_io_client: ^2.0.2

  # Internal dependencies
  kinetix:
    git:
      url: git@github.com:TNT-BOOM-Studio/Kinetix.git
      ref: master

  velix:
    git:
      url: git@github.com:TNT-BOOM-Studio/Velix.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^4.2.0
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  logger: ^2.0.2

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
