name: cengli
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+8

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.2.2
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  flutter_local_notifications: ^12.0.3
  flutter_html: ^3.0.0-beta.2
  expandable: ^5.0.1
  flutter_inappwebview: ^5.7.2+3
  image_picker: ^0.8.7+2
  shimmer: ^2.0.0

  # Date, Time
  intl: ^0.18.1
  syncfusion_flutter_datepicker: ^20.4.54
  flutter_cupertino_datetime_picker: ^3.0.0

  # State
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0
  provider: ^6.0.5

  # Injector
  get_it: ^7.2.0

  # Firebase
  cloud_firestore: ^4.9.2
  firebase_remote_config: ^4.2.6
  firebase_core: ^2.16.0
  firebase_dynamic_links: ^5.3.7
  firebase_messaging: ^14.1.0

  # Model
  equatable: ^2.0.3
  json_serializable: ^6.6.0
  json_annotation: ^4.8.0
  sqflite: ^2.2.6
  uuid: ^3.0.7
  shared_preferences: ^2.2.1

  # Network
  dio: ^4.0.6
  local_auth: ^2.1.7
  eth_sig_util: ^0.0.9
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.7

  # Web3
  crypto: ^3.0.3
  ethers: ^0.0.1+3
  http: ^0.13.4
  web3dart: ^2.5.2
  bip32: ^2.0.0
  bip39: ^1.0.6

  # Push Protocol
  hex: ^0.2.0
  pointycastle: ^3.7.3
  openpgp: ^3.7.0
  cryptography: ^2.5.0
  dart_pg: ^1.1.5
  encrypt: ^5.0.1
  flutter_webrtc: ^0.9.36
  ethereum_addresses: ^1.0.2
  socket_io_client: ^2.0.2

  # Qr
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1

  # Internal dependencies
  kinetix:
    git:
      url: git@github.com:TNT-BOOM-Studio/Kinetix.git
      ref: master

  velix:
    git:
      url: git@github.com:TNT-BOOM-Studio/Velix.git
      ref: main
  dartx: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^4.2.0
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  logger: ^2.0.2

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Unbounded
      fonts:
        - asset: assets/fonts/Unbounded-Regular.ttf
          weight: 400
        - asset: assets/fonts/Unbounded-Medium.ttf
          weight: 500
        - asset: assets/fonts/Unbounded-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Unbounded-Bold.ttf
          weight: 700
