/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICCTPAdapter } from "./ICCTPAdapter";
export type { IERC20 } from "./IERC20";
export type { IInterchainGasPaymaster } from "./IInterchainGasPaymaster";
export type { USDCTransferCengli } from "./USDCTransferCengli";
